"use client";

import { useState, useEffect } from "react";
import { generateSKU } from "../lib/sku-generator";
import { 
  fetchCategoriesFromSupabase, 
  createCategoryInSupabase,
  fetchUnitsFromSupabase,
  createUnitInSupabase
} from "../lib/supabase";

type MaterialAddFormProps = {
  onSubmit: (formData: FormData) => void;
  params: {
    status?: string;
    field?: string;
    message?: string;
  };
};

export function MaterialAddForm({ onSubmit, params }: MaterialAddFormProps) {
  const [category, setCategory] = useState("");
  const [unit, setUnit] = useState("");
  const [sku, setSku] = useState("");
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [categories, setCategories] = useState<string[]>([]);
  const [categoriesLoading, setCategoriesLoading] = useState(true);
  const [units, setUnits] = useState<string[]>([]);
  const [unitsLoading, setUnitsLoading] = useState(true);
  const [showAddCategoryModal, setShowAddCategoryModal] = useState(false);
  const [showAddUnitModal, setShowAddUnitModal] = useState(false);
  const [newCategoryName, setNewCategoryName] = useState("");
  const [newCategoryError, setNewCategoryError] = useState("");
  const [newUnitName, setNewUnitName] = useState("");
  const [newUnitError, setNewUnitError] = useState("");

  const validationFieldName =
    params.status === "validation" && params.field ? params.field.toUpperCase() : null;

  // Load categories and units on mount
  useEffect(() => {
    const loadData = async () => {
      setCategoriesLoading(true);
      const { data, error } = await fetchCategoriesFromSupabase();
      if (!error) {
        setCategories(data || []);
      }
      setCategoriesLoading(false);

      setUnitsLoading(true);
      const { data: unitsData, error: unitsError } = await fetchUnitsFromSupabase();
      if (!unitsError) {
        setUnits(unitsData || []);
      }
      setUnitsLoading(false);
    };
    loadData();
  }, []);

  const handleCategoryChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newCategory = e.target.value;
    setCategory(newCategory);

    // Auto-generate SKU when category changes
    if (newCategory.trim()) {
      const generatedSku = generateSKU(newCategory);
      setSku(generatedSku);
      setAutoGenerated(true);
    }
  };

  const handleSkuChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSku(e.target.value);
    setAutoGenerated(false);
  };

  const handleRegenerateSku = () => {
    if (category.trim()) {
      const generatedSku = generateSKU(category);
      setSku(generatedSku);
      setAutoGenerated(true);
    }
  };

  const handleAddNewCategory = async () => {
    const trimmedName = newCategoryName.trim();
    if (!trimmedName) {
      setNewCategoryError("Category name is required");
      return;
    }

    const { error } = await createCategoryInSupabase(trimmedName);
    if (error) {
      setNewCategoryError(error);
      return;
    }

    // Add to local state
    setCategories([...categories, trimmedName].sort());
    setCategory(trimmedName);

    // Auto-generate SKU for new category
    const generatedSku = generateSKU(trimmedName);
    setSku(generatedSku);
    setAutoGenerated(true);

    // Close modal
    setShowAddCategoryModal(false);
    setNewCategoryName("");
    setNewCategoryError("");
  };

  const handleAddNewUnit = async () => {
    const trimmedName = newUnitName.trim();
    if (!trimmedName) {
      setNewUnitError("Unit name is required");
      return;
    }

    const { error } = await createUnitInSupabase(trimmedName);
    if (error) {
      setNewUnitError(error);
      return;
    }

    // Add to local state
    setUnits([...units, trimmedName].sort());
    setUnit(trimmedName);

    // Close modal
    setShowAddUnitModal(false);
    setNewUnitName("");
    setNewUnitError("");
  };

  return (
    <>
      {params.status === "success" ? (
        <p className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          Material added successfully.
        </p>
      ) : null}

      {params.status === "deleted" ? (
        <p className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          Material deleted successfully.
        </p>
      ) : null}

      {validationFieldName ? (
        <p className="mt-4 rounded-xl border border-amber-400/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-200">
          Missing required field: {validationFieldName}.
        </p>
      ) : null}

      {params.status === "error" ? (
        <p className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-2 text-sm text-red-200">
          Unable to add material right now. {params.message ?? "Please try again."}
        </p>
      ) : null}

      <form action={onSubmit} className="mt-5 grid gap-4 md:grid-cols-2">
        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Name *</span>
          <input
            name="name"
            type="text"
            required
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-slate-300">Category *</span>
            <button
              type="button"
              onClick={() => setShowAddCategoryModal(true)}
              className="text-xs font-semibold text-cyan-300 hover:text-cyan-200"
            >
              + New
            </button>
          </div>
          <select
            name="category"
            value={category}
            onChange={handleCategoryChange}
            required
            disabled={categoriesLoading}
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none disabled:opacity-50"
          >
            <option value="">
              {categoriesLoading ? "Loading categories..." : "Select a category"}
            </option>
            {categories.map((cat) => (
              <option key={cat} value={cat}>
                {cat}
              </option>
            ))}
          </select>
        </label>

        <label className="grid gap-2 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-slate-300">SKU *</span>
            {autoGenerated && (
              <span className="text-xs text-cyan-300">Auto-generated</span>
            )}
          </div>
          <div className="flex gap-2">
            <input
              name="sku"
              type="text"
              value={sku}
              onChange={handleSkuChange}
              required
              className="w-full rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
            />
            <button
              type="button"
              onClick={handleRegenerateSku}
              disabled={!category.trim()}
              className="rounded-xl border border-cyan-400/30 px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-[#111a2f] disabled:opacity-50 disabled:cursor-not-allowed"
            >
              ↻
            </button>
          </div>
        </label>

        <label className="grid gap-2 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-slate-300">Unit *</span>
            <button
              type="button"
              onClick={() => setShowAddUnitModal(true)}
              className="text-xs font-semibold text-cyan-300 hover:text-cyan-200"
            >
              + New
            </button>
          </div>
          <select
            name="unit"
            value={unit}
            onChange={(e) => setUnit(e.target.value)}
            required
            disabled={unitsLoading}
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none disabled:opacity-50"
          >
            <option value="">
              {unitsLoading ? "Loading units..." : "Select a unit"}
            </option>
            {units.map((u) => (
              <option key={u} value={u}>
                {u}
              </option>
            ))}
          </select>
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Color (optional)</span>
          <input
            name="color"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Scan Code (optional)</span>
          <input
            name="scan_code"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">QR Code (optional)</span>
          <input
            name="qr_code"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="flex items-center gap-2 text-sm text-slate-300">
          <input
            name="active"
            type="checkbox"
            defaultChecked
            className="h-4 w-4 rounded border border-cyan-300/40 bg-[#050914] text-cyan-300"
          />
          Active
        </label>

        <div className="md:col-span-2">
          <button
            type="submit"
            className="rounded-xl border border-cyan-400/60 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 hover:bg-cyan-500/20"
          >
            Add Material
          </button>
        </div>
      </form>

      {/* Add Category Modal */}
      {showAddCategoryModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
          <div className="w-full max-w-md rounded-2xl border border-cyan-500/20 bg-[#0c1426] p-6">
            <h3 className="text-lg font-semibold text-white">Add New Category</h3>

            {newCategoryError && (
              <p className="mt-3 rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-2 text-sm text-red-200">
                {newCategoryError}
              </p>
            )}

            <label className="mt-4 grid gap-2 text-sm">
              <span className="text-slate-300">Category Name *</span>
              <input
                type="text"
                value={newCategoryName}
                onChange={(e) => {
                  setNewCategoryName(e.target.value);
                  setNewCategoryError("");
                }}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    handleAddNewCategory();
                  }
                }}
                placeholder="e.g. Steel, Wood, Concrete"
                className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
                autoFocus
              />
            </label>

            <div className="mt-6 flex gap-3">
              <button
                type="button"
                onClick={handleAddNewCategory}
                className="flex-1 rounded-xl border border-cyan-400/60 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 hover:bg-cyan-500/20"
              >
                Add
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowAddCategoryModal(false);
                  setNewCategoryName("");
                  setNewCategoryError("");
                }}
                className="flex-1 rounded-xl border border-slate-400/30 bg-slate-500/10 px-4 py-2 text-sm font-semibold text-slate-300 hover:bg-slate-500/20"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Unit Modal */}
      {showAddUnitModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
          <div className="w-full max-w-md rounded-2xl border border-cyan-500/20 bg-[#0c1426] p-6">
            <h3 className="text-lg font-semibold text-white">Add New Unit</h3>

            {newUnitError && (
              <p className="mt-3 rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-2 text-sm text-red-200">
                {newUnitError}
              </p>
            )}

            <label className="mt-4 grid gap-2 text-sm">
              <span className="text-slate-300">Unit Name *</span>
              <input
                type="text"
                value={newUnitName}
                onChange={(e) => {
                  setNewUnitName(e.target.value);
                  setNewUnitError("");
                }}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    handleAddNewUnit();
                  }
                }}
                placeholder="e.g. Feet, Pounds, Sheets"
                className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
                autoFocus
              />
            </label>

            <div className="mt-6 flex gap-3">
              <button
                type="button"
                onClick={handleAddNewUnit}
                className="flex-1 rounded-xl border border-cyan-400/60 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 hover:bg-cyan-500/20"
              >
                Add
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowAddUnitModal(false);
                  setNewUnitName("");
                  setNewUnitError("");
                }}
                className="flex-1 rounded-xl border border-slate-400/30 bg-slate-500/10 px-4 py-2 text-sm font-semibold text-slate-300 hover:bg-slate-500/20"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
