"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { generateSKU } from "../lib/sku-generator";
import {
  fetchCategoriesWithUnitsFromSupabase,
  fetchUnitsFromSupabase,
} from "../lib/supabase";

type CategoryData = {
  name: string;
  description?: string | null;
  unit_name?: string | null;
};

type MaterialAddFormProps = {
  onSubmit: (formData: FormData) => void;
  params: {
    status?: string;
    field?: string;
    message?: string;
  };
};

export function MaterialAddForm({ onSubmit, params }: MaterialAddFormProps) {
  const [category, setCategory] = useState("");
  const [unit, setUnit] = useState("");
  const [sku, setSku] = useState("");
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [categories, setCategories] = useState<CategoryData[]>([]);
  const [categoriesLoading, setCategoriesLoading] = useState(true);
  const [units, setUnits] = useState<string[]>([]);
  const [unitsLoading, setUnitsLoading] = useState(true);
  const [isUnitLocked, setIsUnitLocked] = useState(false);

  // Create a mapping of category names to their assigned units
  const categoryUnitMap = categories.reduce(
    (acc, cat) => {
      if (cat.unit_name) {
        acc[cat.name] = cat.unit_name;
      }
      return acc;
    },
    {} as Record<string, string>
  );

  const validationFieldName =
    params.status === "validation" && params.field ? params.field.toUpperCase() : null;

  useEffect(() => {
    const loadData = async () => {
      setCategoriesLoading(true);
      const { data: categoryData, error: categoryError } = await fetchCategoriesWithUnitsFromSupabase();
      if (!categoryError) {
        setCategories(categoryData ?? []);
      }
      setCategoriesLoading(false);

      setUnitsLoading(true);
      const { data: unitData, error: unitError } = await fetchUnitsFromSupabase();
      if (!unitError) {
        setUnits(unitData ?? []);
      }
      setUnitsLoading(false);
    };

    void loadData();
  }, []);

  const handleCategoryChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const newCategory = event.target.value;
    setCategory(newCategory);

    // Auto-set and lock unit if category has a mapped unit
    const mappedUnit = categoryUnitMap[newCategory];
    if (mappedUnit) {
      setUnit(mappedUnit);
      setIsUnitLocked(true);
    } else {
      setUnit("");
      setIsUnitLocked(false);
    }

    if (newCategory.trim()) {
      const generatedSku = generateSKU(newCategory);
      setSku(generatedSku);
      setAutoGenerated(true);
    }
  };

  const handleSkuChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSku(event.target.value);
    setAutoGenerated(false);
  };

  const handleRegenerateSku = () => {
    if (!category.trim()) {
      return;
    }

    const generatedSku = generateSKU(category);
    setSku(generatedSku);
    setAutoGenerated(true);
  };

  const qrPreviewUrl = sku.trim()
    ? `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(sku.trim())}`
    : "";

  return (
    <>
      {params.status === "success" ? (
        <p className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          Material added successfully.
        </p>
      ) : null}

      {params.status === "deleted" ? (
        <p className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          Material deleted successfully.
        </p>
      ) : null}

      {validationFieldName ? (
        <p className="mt-4 rounded-xl border border-amber-400/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-200">
          Missing required field: {validationFieldName}.
        </p>
      ) : null}

      {params.status === "error" ? (
        <p className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-2 text-sm text-red-200">
          Unable to add material right now. {params.message ?? "Please try again."}
        </p>
      ) : null}

      <form action={onSubmit} className="mt-5 grid gap-4 md:grid-cols-2">
        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Name *</span>
          <input
            name="name"
            type="text"
            required
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-slate-300">Category *</span>
            <Link
              href="/categories"
              className="text-xs font-semibold text-cyan-300 hover:text-cyan-200"
            >
              + New
            </Link>
          </div>
          <select
            name="category"
            value={category}
            onChange={handleCategoryChange}
            required
            disabled={categoriesLoading}
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white focus:border-cyan-300 focus:outline-none disabled:opacity-50"
          >
            <option value="">
              {categoriesLoading ? "Loading categories..." : "Select a category"}
            </option>
            {categories.map((categoryOption) => (
              <option key={categoryOption.name} value={categoryOption.name}>
                {categoryOption.name}
              </option>
            ))}
          </select>
        </label>

        <label className="grid gap-2 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-slate-300">SKU *</span>
            {autoGenerated ? (
              <span className="text-xs text-cyan-300">Auto-generated</span>
            ) : null}
          </div>
          <div className="flex gap-2">
            <input
              name="sku"
              type="text"
              value={sku}
              onChange={handleSkuChange}
              required
              className="w-full rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
            />
            <button
              type="button"
              onClick={handleRegenerateSku}
              disabled={!category.trim()}
              className="rounded-xl border border-cyan-400/30 px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-[#111a2f] disabled:cursor-not-allowed disabled:opacity-50"
            >
              ↻
            </button>
          </div>
        </label>

        <label className="grid gap-2 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-slate-300">
              Unit *
              {isUnitLocked && (
                <span className="ml-2 text-xs font-semibold text-cyan-300">(locked)</span>
              )}
            </span>
            {!isUnitLocked && (
              <Link
                href="/units"
                className="text-xs font-semibold text-cyan-300 hover:text-cyan-200"
              >
                + New
              </Link>
            )}
          </div>
          <select
            name="unit"
            value={unit}
            onChange={(event) => setUnit(event.target.value)}
            required
            disabled={unitsLoading || isUnitLocked}
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white focus:border-cyan-300 focus:outline-none disabled:opacity-50"
          >
            <option value="">
              {unitsLoading ? "Loading units..." : "Select a unit"}
            </option>
            {units.map((unitOption) => (
              <option key={unitOption} value={unitOption}>
                {unitOption}
              </option>
            ))}
          </select>
          {isUnitLocked && <input type="hidden" name="unit" value={unit} />}
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Color (optional)</span>
          <input
            name="color"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Scan Code (optional)</span>
          <input
            name="scan_code"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">QR Code (optional)</span>
          <input
            name="qr_code"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="flex items-center gap-2 text-sm text-slate-300">
          <input
            name="active"
            type="checkbox"
            defaultChecked
            className="h-4 w-4 rounded border border-cyan-300/40 bg-[#050914] text-cyan-300"
          />
          Active
        </label>

        <div className="md:col-span-2">
          <button
            type="submit"
            className="rounded-xl border border-cyan-400/60 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 hover:bg-cyan-500/20"
          >
            Add Material
          </button>
        </div>

        {qrPreviewUrl ? (
          <div className="md:col-span-2 rounded-2xl border border-cyan-500/20 bg-[#0c1426]/80 p-5">
            <p className="text-sm text-slate-400 mb-3">QR Code Preview</p>
            <div className="inline-block rounded-xl bg-white p-3">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={qrPreviewUrl}
                alt="QR preview"
                width={170}
                height={170}
              />
            </div>
            <p className="mt-2 text-xs text-slate-500">Generated from SKU: {sku}</p>
          </div>
        ) : null}
      </form>
    </>
  );
}
