"use client";

import { useState } from "react";
import { generateSKU } from "../lib/sku-generator";

type MaterialAddFormProps = {
  onSubmit: (formData: FormData) => void;
  params: {
    status?: string;
    field?: string;
    message?: string;
  };
};

export function MaterialAddForm({ onSubmit, params }: MaterialAddFormProps) {
  const [category, setCategory] = useState("");
  const [sku, setSku] = useState("");
  const [autoGenerated, setAutoGenerated] = useState(false);

  const validationFieldName =
    params.status === "validation" && params.field ? params.field.toUpperCase() : null;

  const handleCategoryChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newCategory = e.target.value;
    setCategory(newCategory);

    // Auto-generate SKU when category changes
    if (newCategory.trim()) {
      const generatedSku = generateSKU(newCategory);
      setSku(generatedSku);
      setAutoGenerated(true);
    }
  };

  const handleSkuChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSku(e.target.value);
    setAutoGenerated(false);
  };

  const handleRegenerateSku = () => {
    if (category.trim()) {
      const generatedSku = generateSKU(category);
      setSku(generatedSku);
      setAutoGenerated(true);
    }
  };

  return (
    <>
      {params.status === "success" ? (
        <p className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          Material added successfully.
        </p>
      ) : null}

      {params.status === "deleted" ? (
        <p className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          Material deleted successfully.
        </p>
      ) : null}

      {validationFieldName ? (
        <p className="mt-4 rounded-xl border border-amber-400/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-200">
          Missing required field: {validationFieldName}.
        </p>
      ) : null}

      {params.status === "error" ? (
        <p className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-2 text-sm text-red-200">
          Unable to add material right now. {params.message ?? "Please try again."}
        </p>
      ) : null}

      <form action={onSubmit} className="mt-5 grid gap-4 md:grid-cols-2">
        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Name *</span>
          <input
            name="name"
            type="text"
            required
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Category *</span>
          <input
            name="category"
            type="text"
            value={category}
            onChange={handleCategoryChange}
            required
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-slate-300">SKU *</span>
            {autoGenerated && (
              <span className="text-xs text-cyan-300">Auto-generated</span>
            )}
          </div>
          <div className="flex gap-2">
            <input
              name="sku"
              type="text"
              value={sku}
              onChange={handleSkuChange}
              required
              className="w-full rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
            />
            <button
              type="button"
              onClick={handleRegenerateSku}
              disabled={!category.trim()}
              className="rounded-xl border border-cyan-400/30 px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-[#111a2f] disabled:opacity-50 disabled:cursor-not-allowed"
            >
              ↻
            </button>
          </div>
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Unit *</span>
          <input
            name="unit"
            type="text"
            required
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Color (optional)</span>
          <input
            name="color"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">Scan Code (optional)</span>
          <input
            name="scan_code"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="grid gap-2 text-sm">
          <span className="text-slate-300">QR Code (optional)</span>
          <input
            name="qr_code"
            type="text"
            className="rounded-xl border border-cyan-400/30 bg-[#050914] px-3 py-2 text-white placeholder:text-slate-500 focus:border-cyan-300 focus:outline-none"
          />
        </label>

        <label className="flex items-center gap-2 text-sm text-slate-300">
          <input
            name="active"
            type="checkbox"
            defaultChecked
            className="h-4 w-4 rounded border border-cyan-300/40 bg-[#050914] text-cyan-300"
          />
          Active
        </label>

        <div className="md:col-span-2">
          <button
            type="submit"
            className="rounded-xl border border-cyan-400/60 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 hover:bg-cyan-500/20"
          >
            Add Material
          </button>
        </div>
      </form>
    </>
  );
}
